version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: hs-codes-backend
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - HS_DATA_FILE=hscodes.xlsx
      - EMBEDDING_FILE=hs_embeddings_600970782048097937.pkl
      - PORT=5000
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    volumes:
      - ./hscodes.xlsx:/app/hscodes.xlsx:ro
      - ./hs_embeddings_600970782048097937.pkl:/app/hs_embeddings_600970782048097937.pkl:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend React app
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hs-codes-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: hs-codes-network

volumes:
  # Optional: for persistent data if needed
  backend_cache:
    driver: local